### ISSUE TITLE
Is there any instructions to make this easier to do because i am confused

### ISSUE THREAD

**Issue by CreeperMaster224YT** [Joelrau/iw7-mod#25]
...

**Comment by ethanjones99** [comment]
You need to download Visual Studio 2022 and install it. When it's installed, open Visual Studio, and you should see an option to clone the repository. You can do this by getting the link from the code button on the main page; also, take note of the path because that is where the folder will be created. 

After downloading the files, go into the folder and open the generate.bat file. Once you have done that, a new folder called build will be created. Open the build folder and select iw7-mod.sln, A new instance of Visual Studio will open, select build at the top of Visual Studio (make sure debug is chosen in the drop menu underneath). 

When the build is fully compiled, go back into the build folder, and you should see a new folder called bin open that and the x64 folder inside of bin, then go into debug, and you should see iw7-mod.exe. Copy the exe into your IW game folder, launch the exe, and you're done!

I hope this helps!

**Comment by skkuull** [comment]
There ain't a support as for how to build this as long as its already documented in the readme

**Comment by xGodLike221** [comment]
hi, ive followed ur steps above, but every time i try to launch the exe it says "failed to read game binary" idk how to fix that. how do i get the installation file? apart from buying it on steam,or is the included one enough?

**Comment by xGodLike221** [comment]
Okay, now I can "launch" the game. But everytime I try to launch it, it says "fatal error"
