### ISSUE TITLE
Allow bots even when xblive_privatematch is set to 0 [enhancement ig]

### ISSUE THREAD

**Issue by CrazyCSIW6** [Joelrau/iw7-mod#5]
H1-Mod already does this in ranked.cpp, as seen here:

```
// Always run bots, even if xblive_privatematch is 0
	utils::hook::set(0x2C10B0_b, 0xC301B0); // BG_BotSystemEnabled
	utils::hook::set(0x2C0E60_b, 0xC301B0); // BG_AISystemEnabled
	utils::hook::set(0x2C1040_b, 0xC301B0); // BG_BotFastFileEnabled
	utils::hook::set(0x2C11B0_b, 0xC301B0); // BG_BotsUsingTeamDifficulty

**Comment by VVayve** [comment]
Yess!!! Please do this or allow us to do it! Most people Unlock all in these cod clients and this would be a nice way to have an alternative! Even for us without a decent internet connection!

**Comment by LevelChecker** [comment]
I mean bots technically can still exist in there the problem is that they are freezing completely when you set it to that via console

**Comment by Ston3Cold** [comment]
Yeah, been looking into this myself. Would be awesome if the ability was added to rank up vs bots when using playlists at minimum. Been looking at the playlist file myself since yesterday, but seems like there is no setting there to force start a lobby as single-player like older cod clients (AW and Ghosts). 

Sadly what I know about coding is non-existent, just hope that in the future you guys will consider the playlist rank up option at least for those of that want to play vs bots as that would keep me busy for hours. I never really played this game online when it got released, but have poured MANY hours into the s1x, IW6x and H1 clients due to the fact that we can rank up vs bots in those projects.

Thanks again for creating the mod, still having fun in private match :)

**Comment by CrazyCSIW6** [comment]
> I mean bots technically can still exist in there the problem is that they are freezing completely when you set it to that via console

H1 also did this by default but H1-Mod already solved the problem, which is why I made this issue [to see if the same fixes could be applied to IW7 as well]
