### ISSUE TITLE
EE Characters Not Unlocked

### ISSUE THREAD

**Issue by VERsingthegamez** [Joelrau/iw7-mod#60]
Even after doing all the unlocked commands, I still cannot equip the EE characters by doing their codes. Unless theres another command for them specifically.

**Comment by aeugurauhhr** [comment]
I am pretty sure it's impossible because the stars do not appear in the client unlike the actual steam version of the game. If they did appear and you typed in the unlock commands then they would all appear green, and after that you'd be able to type in the code of the character you want to play as on it's map (e.g. wyler on spaceland) in the pre-game lobby of zombies.

**Comment by mjkzy** [comment]
`unlockstatsEE` & `director_cut 1` are your best friends
